services:
  eureka-server:
    build: .  # 현재 디렉토리에서 빌드
    image: eureka-server:latest
    container_name: eureka-server-app
    ports:
      - "8761:8761"
    networks:
      msa-network:

networks:
  msa-network:
    external: true  # 외부에 이미 정의된 msa-network를 사용