services:
  order-service:
    build: .
    image: order-service:latest
    container_name: order-service-app
    ports:
      - "8082:8082"
    networks:
      - msa-network

networks:
  msa-network:
    external: true  # 외부에 이미 정의된 msa-network를 사용
