server:
  port: 8081  # user-service가 8081에서 실행됨

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-user:3306/userdb
    username: root
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true          # SQL 출력
        format_sql: true        # SQL 포맷팅
        use_sql_comments: true  # SQL에 주석 추가
        default_batch_fetch_size: 1000  # 성능 최적화
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL에 맞는 방언 설정

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-app:8761/eureka/
  instance:
    instance-id: user-service-${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
